[global]
type=global
endpoint_identifier_order=username,ip,anonymous
user_agent=Telephony Platform

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
allow_reload=yes

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0
allow_reload=yes

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0
allow_reload=yes
